### ISSUE TITLE
Windows 에러

### ISSUE THREAD

**Issue by kooBH** [kooBH/cpp_python_wrapping#5]
``` Traceback (most recent call last):
  File ".\test.py", line 5, in <module>
    f = A(5)
  File "C:\project\cpp_python_wrapping\ctype_2d\a.py", line 13, in __init__
    lib.A_new.argtypes = [ctypes.c_int]
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'A_new' not found
```

**Comment by kooBH** [comment]
https://stackoverflow.com/questions/24575348/wrapping-c-functions-in-python-with-ctypes-on-windows-function-not-found

``` __declspec(dllexport)```
